kubernetes:
  host: https://kubernetes.default

helloworld1:
  namespace: default
  image:
    name: tutum/hello-world
    tag: latest
    pullPolicy: IfNotPresent
  service:
    ingressClass: internal-ingress1