---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: example-container
        image: ocp.dev-67.mirror.mavdallas.com:8443/init/mwpcicd/bitnami/nginx:1.21.6-debian-10-r122
        ports:
        - containerPort: 8088
