apiVersion: v2
name: my-e-commerce-solution
description: A Parent Helm chart for Kubernetes
type: application
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates
version: 0.1.0
# All E-Commerce micro-services Helm Charts that are needed
# versions needs to be changed, whenever corresponding the sub chart versions are changing
dependencies:
- name: helloworld
  repository: file://charts/helloworld
  version: 0.1.0
  condition: portal.enabled
- name: helloworld1
  repository: file://charts/helloworld-1
  version: 0.1.0